export const API_ROUTES: Record<Route, ApiRoute> = {
  user: "/newf/me",
  notifications: "/newf/notifications/subscriptions",
  weather: "/weather",
  departure: "/departures",
  planning_today: "/planning/users/:email/courses/today",
  planning_week: "/planning/users/:email/courses",
  planning_sport: "/planning-sport",
  restaurant: "/restaurant",
  restaurantRating: "/restaurant/:id",
  traq: "/traq/",
  translation: "/translate",
  washingMachines: "/washingmachines",
  login: "/auth/login",
  register: "/auth/register",
  logout: "/auth/logout",
  saveToken: "/auth/token",
  saveExpoPushToken: "/auth/expo-push-token",
  verifyCode: "/auth/verification-code",
  verifyAccount: "/auth/verify-account",
  resendCode: "/auth/resend-code",
  resetPassword: "/auth/reset-password",
  changePassword: "/auth/change-password",
  deleteAccount: "/newf/me",
  club: "/club",
  clubDetails: "/club/:id",
  clubMembers: "/club/:id/members",
  clubJoin: "/club/:id/join",
  clubLeave: "/club/:id/leave",
  association: "/association",
  associationDetails: "/association/:id",
  associationMembers: "/association/:id/members",
  associationJoin: "/association/:id/join",
  associationLeave: "/association/:id/leave",
  bassine: "/bassine",
  bassineLeaderboard: "/bassine/leaderboard",
  bassineHistory: "/bassine/history",
  bassineUserHistory: "/bassine/history/:email",
  reservation: "/reservation",
  reservationCategory: "/reservation/category/:id",
  reservationCreateCategory: "/reservation/category",
  reservationItem: "/reservation/item/:id",
  reservationCreateItem: "/reservation/item",
  reservationClub: "/reservation/club/:id",
  reservationAssociation: "/reservation/association/:id",
  reservationMy: "/reservation/me",
  reservationSearch: "/reservation/search",
  event: "/event",
  eventClub: "/event/club/:idclub",
  eventDetails: "/event/:id",
  eventJoin: "/event/:id/join",
  eventLeave: "/event/:id/leave",
  eventMembers: "/event/:id/members",
  schedule_me: "/schedule/me",
  schedule_inte: "/schedule/inte",
  covoiturage: "/carpool",
};

type ApiRoute = `/${string}`;
type Route =
  | "user"
  | "notifications"
  | "weather"
  | "departure"
  | "planning_today"
  | "planning_week"
  | "planning_sport"
  | "restaurant"
  | "restaurantRating"
  | "traq"
  | "translation"
  | "washingMachines"
  | "login"
  | "register"
  | "logout"
  | "saveToken"
  | "saveExpoPushToken"
  | "verifyCode"
  | "verifyAccount"
  | "resendCode"
  | "resetPassword"
  | "changePassword"
  | "deleteAccount"
  | "club"
  | "clubDetails"
  | "clubJoin"
  | "clubLeave"
  | "clubMembers"
  | "bassine"
  | "bassineLeaderboard"
  | "bassineHistory"
  | "bassineUserHistory"
  | "reservation"
  | "reservationCategory"
  | "reservationCreateCategory"
  | "reservationItem"
  | "reservationCreateItem"
  | "reservationClub"
  | "reservationAssociation"
  | "reservationMy"
  | "reservationSearch"
  | "event"
  | "eventClub"
  | "eventDetails"
  | "eventJoin"
  | "eventLeave"
  | "eventMembers"
  | "schedule_me"
  | "schedule_inte"
  | "covoiturage";
