export const QUERY_KEYS = {
  restaurantMenu: ["restaurantMenu"],
  restaurantRating: ["restaurantRating"],
  timetable: ["timetable"],
  homework: ["homework"],
  laundry: ["laundry"],
  weather: ["weather"],
  user: ["user"],
  traq: ["traq"],
  bassine: {
    overview: ["bassine", "overview"],
    leaderboard: ["bassine", "leaderboard"],
    history: ["bassine", "history"],
    userHistory: ["bassine", "history", "user"],
  },
  club: {
    clubs: ["clubs"],
    clubDetails: ["clubDetails"],
    clubJoin: ["clubJoin"],
    clubLeave: ["clubLeave"],
    clubMembers: ["clubMembers"],
  },
  event: {
    events: ["events"],
    clubEvents: ["clubEvents"],
    eventDetails: ["eventDetails"],
    eventJoin: ["eventJoin"],
    eventLeave: ["eventLeave"],
    eventMembers: ["eventMembers"],
  },
  notification: ["notification"],
  auth: {
    user: ["auth", "user"],
    login: ["auth", "login"],
    register: ["auth", "register"],
    saveToken: ["auth", "saveToken"],
    saveExpoPushToken: ["auth", "saveExpoPushToken"],
    resetPassword: ["auth", "resetPassword"],
    changePassword: ["auth", "changePassword"],
  },
  homeWidgetPreferences: ["homeWidgetPreferences"],
  servicePreferences: ["servicePreferences"],
};
