export const QUERY_KEYS = {
  restaurantMenu: ["restaurantMenu"],
  restaurantRating: ["restaurantRating"],
  timetable: ["timetable"],
  homework: ["homework"],
  laundry: ["laundry"],
  weather: ["weather"],
  user: ["user"],
  traq: ["traq"],
  club: {
    clubs: ["clubs"],
    clubDetails: ["clubDetails"],
    clubJoin: ["clubJoin"],
    clubLeave: ["clubLeave"],
    clubMembers: ["clubMembers"],
  },
  notification: ["notification"],
  auth: {
    user: ["auth", "user"],
    login: ["auth", "login"],
    register: ["auth", "register"],
    saveToken: ["auth", "saveToken"],
    saveExpoPushToken: ["auth", "saveExpoPushToken"],
    resetPassword: ["auth", "resetPassword"],
    changePassword: ["auth", "changePassword"],
  },
  homeWidgetPreferences: ["homeWidgetPreferences"],
  servicePreferences: ["servicePreferences"],
  reservation: {
    categories: ["reservation", "categories"],
    createCategory: ["reservation", "createCategory"],
    items: ["reservation", "items"],
    item: (id: number, date?: string) => ["reservation", "items", id, date],
    createItem: ["reservation", "createItem"],
    club: (id: number) => ["reservation", "club", id],
    my: (time?: "all" | "past" | "current") => [
      "reservation",
      "my",
      time || "current",
    ],
    search: (q: string) => ["reservation", "search", q],
  },
};
