export const QUERY_KEYS = {
  restaurantMenu: ["restaurantMenu"],
  restaurantRating: ["restaurantRating"],
  timetable: ["timetable"],
  schedule: ["schedule"],
  schedule: ["schedule"],
  schedule: ["schedule"],
  homework: ["homework"],
  laundry: ["laundry"],
  weather: ["weather"],
  user: ["user"],
  traq: ["traq"],
  bassine: {
    overview: ["bassine", "overview"],
    leaderboard: ["bassine", "leaderboard"],
    history: ["bassine", "history"],
    userHistory: ["bassine", "history", "user"],
  },
  club: {
    clubs: ["clubs"],
    clubDetails: ["clubDetails"],
    clubJoin: ["clubJoin"],
    clubLeave: ["clubLeave"],
    clubMembers: ["clubMembers"],
  },
  association: {
    associations: ["associations"],
    associationDetails: ["associationDetails"],
    associationJoin: ["associationJoin"],
    associationLeave: ["associationLeave"],
    associationMembers: ["associationMembers"],
  },
  event: {
    events: ["events"],
    clubEvents: ["clubEvents"],
    eventDetails: ["eventDetails"],
    eventJoin: ["eventJoin"],
    eventLeave: ["eventLeave"],
    eventMembers: ["eventMembers"],
  },
  notification: ["notification"],
  auth: {
    user: ["auth", "user"],
    login: ["auth", "login"],
    register: ["auth", "register"],
    saveToken: ["auth", "saveToken"],
    saveExpoPushToken: ["auth", "saveExpoPushToken"],
    resetPassword: ["auth", "resetPassword"],
    changePassword: ["auth", "changePassword"],
  },
  homeWidgetPreferences: ["homeWidgetPreferences"],
  servicePreferences: ["servicePreferences"],
  reservation: {
    categories: ["reservation", "categories"],
    createCategory: ["reservation", "createCategory"],
    items: ["reservation", "items"],
    item: (id: number, date?: string) => ["reservation", "items", id, date],
    createItem: ["reservation", "createItem"],
    club: (id: number) => ["reservation", "club", id],
    association: (id: number) => ["reservation", "association", id],
    my: (time?: "all" | "past" | "current") => [
      "reservation",
      "my",
      time || "current",
    ],
    search: (q: string) => ["reservation", "search", q],
  },
  covoiturage: {
    covoiturages: ["covoiturage"],
  }
};
