import type { Homework } from "@/dto";

export const getHomeworks = async (userId: number): Promise<Homework[]> => {
  await new Promise((res) => setTimeout(res, 500));

  return [
    {
      id: 1,
      author: userId,
      course_name: "Mathématiques",
      title: "Exercice sur les intégrales",
      description: "Faire les exercices 3 à 6 du chapitre 4.",
      deadline: new Date(Date.now() + 2 * 86400000),
      done: false,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 2,
      author: userId,
      course_name: "Physique",
      title: "Compte-rendu TP optique",
      description: "Remettre un PDF avec les mesures et calculs.",
      deadline: new Date(Date.now() + 4 * 86400000),
      done: false,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 4,
      author: userId,
      course_name: "Informatique",
      title: "Projet de programmation",
      description: "Développer une application de gestion de tâches.",
      deadline: new Date(Date.now() + 7 * 86400000),
      done: false,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 3,
      author: userId,
      course_name: "Chimie",
      title: "Rapport de laboratoire",
      description: "Analyser les résultats des expériences de la semaine.",
      deadline: new Date(Date.now() + 3 * 86400000),
      done: false,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 5,
      author: userId,
      course_name: "Histoire",
      title: "Devoir sur la Révolution française",
      description:
        "Rédiger un essai de 1500 mots sur les causes et conséquences.",
      deadline: new Date(Date.now() + 5 * 86400000),
      done: false,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 6,
      author: userId,
      course_name: "Biologie",
      title: "Étude de cas sur l'écosystème local",
      description:
        "Préparer une présentation sur la biodiversité de la région.",
      deadline: new Date(Date.now() + 6 * 86400000),
      done: false,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 7,
      author: userId,
      course_name: "Philosophie",
      title: "Analyse d'un texte philosophique",
      description:
        "Rédiger une critique du texte de Kant sur la morale. Rédiger une critique du texte de Kant sur la morale. Rédiger une critique du texte de Kant sur la morale. Rédiger une critique du texte de Kant sur la morale.",
      deadline: new Date(Date.now() + 8 * 86400000),
      done: false,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 8,
      author: userId,
      course_name: "Histoire de l'art",
      title: "Analyse d'une œuvre d'art",
      description:
        "Choisir une œuvre et en faire une analyse détaillée de ses éléments.",
      deadline: new Date(Date.now() + 2 * 86900000),
      done: false,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 9,
      author: userId,
      course_name: "Géographie",
      title: "Étude d'un territoire",
      description: "Préparer un exposé sur les enjeux géopolitiques actuels.",
      deadline: new Date(Date.now() - 9 * 86400000),
      done: false,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 10,
      author: userId,
      course_name: "Économie",
      title: "Analyse d'un marché",
      description: "Étudier les tendances du marché local et global.",
      deadline: new Date(Date.now() - 17 * 86400000),
      done: false,
      created_at: new Date(),
      updated_at: new Date(),
    },
  ];
};
